# Training params
use_cuda: true
batch_size: 2
num_workers: 0
lr_init: 1.0e-3
lr_decay_rate: 0.1
lr_decay_steps: 500
training_steps: 500
warmup_steps: 0
# Evaluation
loss_report_step: 100
log_grad: True
log_grad_step: 100
save_model_step: 100
eval_step: 100
rollout_steps: 10
run_validate: true
num_eval_rollout: 2
save_video: true
# Dataset
data_path: "test_datasets/rigidFall_epLen_100_inter_10_totalSteps_500.npz"
test_data_path: "test_datasets/rigidFall_epLen_100_inter_10_totalSteps_500.npz"
data_config:
  noise_std: 3.0e-5
  connectivity_radius: 0.01
  input_seq_length: 3
# Logging
logging_folder: "log_test"
log_level: "info"
continue_log_from: "2024-09-23-15:48"
# model_file: "log_test/2024-09-23-15:48/models/weights_itr_100.ckpt"
# train_state_file: "log_test/2024-09-23-15:48/models/train_state_itr_100.ckpt"
# Simulator params
leave_out_mm: True
latent_dim: 128
message_passing_steps: 10
mlp_layers: 2
