# Training params
use_cuda: true
batch_size: 32
num_workers: 8
lr_init: 1.0e-3
lr_decay_rate: 0.1
lr_decay_steps: 1.0e+6
training_steps: 1.0e+6
warmup_steps: 1
# Evaluation
loss_report_step: 2000
log_grad: True
log_grad_step: 10000
save_model_step: 2000
eval_step: 2000
rollout_steps: 50
run_validate: true
num_eval_rollout: 10
save_video: true
# Dataset
data_path: "datasets/rigidFall_epLen_100_inter_10_totalSteps_100K"
test_data_path: "datasets/rigidFall_epLen_100_inter_10_totalSteps_10K.npz"

simulator:
  collision_radius: 0.01
  input_seq_length: 3
  graph_builder:
    type: 'fig'
    noise_std: 3.0e-5
# Logging
logging_folder: "log"
log_level: "info"
# GNN params
latent_dim: 128
message_passing_steps: 10
mlp_layers: 2
